name: squirrel_pot
description: Squirrel pot is a storage optimiser.
version: 1.0.0
repository: https://github.com/Snaptech-Labs/Squirrel-Pot

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
